
db:
  image: mysql
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=your_root_password
    - MYSQL_DATABASE=docker_rails
    - MYSQL_USER=docker_rails_user
    - MYSQL_PASSWORD=docker_rails_user_pw
    
redis:
  image: redis
  ports:
    - "6379"
    
sidekiq:
  build: .
  working_dir: /usr/src/app
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - db:db
    - redis:redis
  volumes_from:
    - docker-rails
  volumes:
    - ~/.awssecret:/root/.awssecret

web:
  build: .
  working_dir: /usr/src/app
  volumes_from:
    - docker-rails
  volumes: 
    - ~/.awssecret:/root/.awssecret
  ports:
    - "3000:3000"
  links:
    - db:db
    - redis:redis
  