# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d30526705f55a4a76f1fec93c386dfce0a459f9446b81c65258bbd41fa77476869c14a740208f7a2d70109eeed79ebd0d6349c5e6fd86215eb23197f55b966

test:
  secret_key_base: 80836503c337c3bade1a0f3278c9574baf1881fcbd332658864984f3a42ae10e817397e710e5e69084f47def13235d441e2bddad3c94cc002002c40f023e9e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
